### ISSUE TITLE
srun interactive use add timelimit

### ISSUE THREAD

**Issue by tobigithub** [ucdavis-bioinformatics-training/A-Primer-on-Using-the-Bioinformatics-Core-Administrated-Servers-and-Cluster-s-#1]
Hi,
see course PPT/PDF on page 40, interactive use requires time limit to be set, otherwise
"srun: error: Unable to allocate resources: Requested time limit is invalid (missing or exceeds some limit)"
Solutions, commands should be updated to work on the GC cluster. Add  "--time=10:00"
Tobias

**Comment by msettles** [comment]
Thanks Tobias
